services:
  park4mikines:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: park4mikines
    restart: always
    network_mode: "host" # Optimized for LXC
    environment:
      - DATABASE_URL=${DATABASE_URL:-file:/app/prisma/dev.db}
      - JWT_SECRET=${JWT_SECRET}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    volumes:
      - ./prisma/dev.db:/app/prisma/dev.db
      - ./public/uploads:/app/public/uploads
